apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: product-ingestion
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["delete", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  resourceNames: ["outfit-creator-service"]
  verbs: ["get", "patch"]