# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: outfit-creator-service
replicaCount: 1
autoScaling:
  minReplicas: 1
  maxReplicas: 2
  cpuTargetPercentage: 85
image:
  repository: localhost:5000/products
  tag: latest
  pullPolicy: IfNotPresent
  config:
    - env: search_auth
      secretKey: search_auth
    - env: MONGODB_CLIENT
      secretKey: mongodb_client